# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ldt < Formula
  desc ""
  homepage "https://github.com/pixelboehm/ldt"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.1.5/ldt_Darwin_arm64.tar.gz"
      sha256 "ec5f1ababa3c9d7002e0496d573bacfff654dd936e3e2e1e163398a33c690ee8"

      def install
        bin.install "lightbulb"
        bin.install "switch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.1.5/ldt_Darwin_x86_64.tar.gz"
      sha256 "0ef426dcccca44280e0c2ad6c71fd39f4cab5b35812ec993e255367aab34d095"

      def install
        bin.install "lightbulb"
        bin.install "switch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.1.5/ldt_Linux_arm64.tar.gz"
      sha256 "aa91ddfc9796baf9452592e9f217a768773c6b4676c960b198bdf4e699524d66"

      def install
        bin.install "lightbulb"
        bin.install "switch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.1.5/ldt_Linux_x86_64.tar.gz"
      sha256 "1f1fe36423eaf233a73a3fe42d6d3c25eb53855aa64210c30788868bfb44484b"

      def install
        bin.install "lightbulb"
        bin.install "switch"
      end
    end
  end
end
