# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lightbulb < Formula
  desc ""
  homepage "https://github.com/pixelboehm/ldt"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.9.0/lightbulb_Darwin_x86_64.tar.gz"
      sha256 "557a24b12e10ae7b2992ea05645b3d2e50286e8a9f771f24e50ae3d28f8d9cb5"

      def install
        bin.install "lightbulb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.9.0/lightbulb_Darwin_arm64.tar.gz"
      sha256 "f4f4b7bbbe94a4b171f42f07324b34b8424f131eb3c81e6e19a45223b75a8289"

      def install
        bin.install "lightbulb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.9.0/lightbulb_Linux_arm64.tar.gz"
      sha256 "3cc76019ea9a589e4595b3aba9467bdfde71cdc9c0be5038bb668c49ab0d7639"

      def install
        bin.install "lightbulb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.9.0/lightbulb_Linux_x86_64.tar.gz"
      sha256 "087ba35d6b3266710146ed27a625af0cfdd879cda9814b537b7ede6897dc39aa"

      def install
        bin.install "lightbulb"
      end
    end
  end
end
