# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrchestrationManager < Formula
  desc ""
  homepage "https://github.com/pixelboehm/longevity"
  version "0.13.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pixelboehm/longevity/releases/download/v0.13.1/orchstration-manager_Darwin_x86_64.tar.gz"
      sha256 "8c67b94412bee2edb31aa43c9aa2590584a024da050cf54e0efd13d0d86af9b5"

      def install
        system "mkdir", "-p" "/usr/local/etc/orchestration-manager"
        system "touch", "/usr/local/etc/orchestration-manager/ldt.list"
        bin.installorchstration-manager
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pixelboehm/longevity/releases/download/v0.13.1/orchstration-manager_Darwin_arm64.tar.gz"
      sha256 "bd4191b5fbc2ac478c664d33b91f8278bc3ada0cefdba4e008cabe30258d858a"

      def install
        system "mkdir", "-p" "/usr/local/etc/orchestration-manager"
        system "touch", "/usr/local/etc/orchestration-manager/ldt.list"
        bin.installorchstration-manager
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixelboehm/longevity/releases/download/v0.13.1/orchstration-manager_Linux_arm64.tar.gz"
      sha256 "31fb92603b0d14736e5da68781507a881050fb55e59cfc5ab727891b22cd3593"

      def install
        system "mkdir", "-p" "/usr/local/etc/orchestration-manager"
        system "touch", "/usr/local/etc/orchestration-manager/ldt.list"
        bin.installorchstration-manager
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pixelboehm/longevity/releases/download/v0.13.1/orchstration-manager_Linux_x86_64.tar.gz"
      sha256 "8db8cd7e4e7a73978ae8b387653bc6ba0c35bc1fa7dfb199e918e46998f607b4"

      def install
        system "mkdir", "-p" "/usr/local/etc/orchestration-manager"
        system "touch", "/usr/local/etc/orchestration-manager/ldt.list"
        bin.installorchstration-manager
      end
    end
  end
end
