# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OrchestrationManager < Formula
  desc ""
  homepage "https://github.com/pixelboehm/longevity"
  version "0.15.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pixelboehm/longevity/releases/download/v0.15.0/orchstration-manager_Darwin_arm64.tar.gz"
      sha256 "c577ea2f184d7f9f08714da27fdcc1c09088f7063f2a2ed45b5bd2f9761eb169"

      def install
        system "mkdir", "-p" "/usr/local/etc/orchestration-manager"
        system "touch", "/usr/local/etc/orchestration-manager/ldt.list"
        bin.installorchstration-manager
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pixelboehm/longevity/releases/download/v0.15.0/orchstration-manager_Darwin_x86_64.tar.gz"
      sha256 "bddaa412cd0bc91211bff97b5d29a81895ba29d0e5e29347a3941ca5784bed81"

      def install
        system "mkdir", "-p" "/usr/local/etc/orchestration-manager"
        system "touch", "/usr/local/etc/orchestration-manager/ldt.list"
        bin.installorchstration-manager
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixelboehm/longevity/releases/download/v0.15.0/orchstration-manager_Linux_arm64.tar.gz"
      sha256 "18a8c04eb77f398f5db3d82e6da83d3270b4979e5c483cb62fa5d7cf6ad7b66f"

      def install
        system "mkdir", "-p" "/usr/local/etc/orchestration-manager"
        system "touch", "/usr/local/etc/orchestration-manager/ldt.list"
        bin.installorchstration-manager
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pixelboehm/longevity/releases/download/v0.15.0/orchstration-manager_Linux_x86_64.tar.gz"
      sha256 "925a01821d2c13a15cd38306ee4956e9cf2e5d22a48743070e4b7b879b9a6f9b"

      def install
        system "mkdir", "-p" "/usr/local/etc/orchestration-manager"
        system "touch", "/usr/local/etc/orchestration-manager/ldt.list"
        bin.installorchstration-manager
      end
    end
  end
end
