# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Switch < Formula
  desc ""
  homepage "https://github.com/pixelboehm/ldt"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.5.0/switch_Darwin_x86_64.tar.gz"
      sha256 "d519b91fa6410ef25002f40fa371bb685dc1620ef64911373963f73b05258036"

      def install
        bin.install "switch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.5.0/switch_Darwin_arm64.tar.gz"
      sha256 "9c89e387c4e2d5672e951f0c6fff74361508f835330574b625baf9e64beec7ba"

      def install
        bin.install "switch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.5.0/switch_Linux_arm64.tar.gz"
      sha256 "22ad21eb7ad58717ee6541f13074a26485df61f12984dfd7fce6a67795f9feba"

      def install
        bin.install "switch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.5.0/switch_Linux_x86_64.tar.gz"
      sha256 "78cc18c1fe10fba258d57cca5052b2d649a75cbde3d8bd8330c578f03cda78af"

      def install
        bin.install "switch"
      end
    end
  end
end
