# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Switch < Formula
  desc ""
  homepage "https://github.com/pixelboehm/ldt"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.9.0/switch_Darwin_x86_64.tar.gz"
      sha256 "afba171419c05ffe221e34281c3cac584688cad69594aeb454181cb96863b94f"

      def install
        bin.install "switch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.9.0/switch_Darwin_arm64.tar.gz"
      sha256 "4627d4dc78d53cd58e449a58cf3ec596890112a2254f4b75e4a3216acd33756c"

      def install
        bin.install "switch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.9.0/switch_Linux_arm64.tar.gz"
      sha256 "1324b72b6e7eb340c9323b36c489b4127decd2d3c2845998a323401dcc3a1689"

      def install
        bin.install "switch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pixelboehm/ldt/releases/download/v0.9.0/switch_Linux_x86_64.tar.gz"
      sha256 "abb6479f7cb5a855722374693481b20335a24f02f33f2acd478605528b2fc5df"

      def install
        bin.install "switch"
      end
    end
  end
end
